server:
  host: "0.0.0.0"
  port: 6379
  read_timeout: 30s
  write_timeout: 30s
  max_connections: 10000
  enable_metrics: true
  enable_health: true

store:
  max_memory: "1GB"
  eviction_policy: "lru"
  ttl_enabled: true
  snapshot_enabled: true
  snapshot_path: "./data/snapshot.rdb"
  snapshot_interval: 5m

redis:
  enabled: false
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

api:
  enabled: true
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  cors_enabled: true
  rate_limit: 1000 